# Regina Trigo Zamora
# Quiz 1

In [ ]:
QUIZ_01 = { "A": [7, 1.6, 4, 10, 4.5],
          "B": [9.2, 2.4, 21, 30, 3.5],
          "C": [8, 1.7, 32, 40, 2.5] }

In [ ]:
print(QUIZ_01)

{'A': [7, 1.6, 4, 10, 4.5], 'B': [9.2, 2.4, 21, 30, 3.5], 'C': [8, 1.7, 32, 40, 2.5]}


In [ ]:
import pandas as pd


In [ ]:
Valores = pd.DataFrame(QUIZ_01, index = ["Primero", "Segundo", "Tercero", "Cuarto", "Quinto"])
Valores

A     B     C
Primero   7.0   9.2   8.0
Segundo   1.6   2.4   1.7
Tercero   4.0  21.0  32.0
Cuarto   10.0  30.0  40.0
Quinto    4.5   3.5   2.5

In [ ]:
type(Valores)

pandas.core.frame.DataFrame

In [ ]:
Valores.ndim

2

In [ ]:
Valores["A"]

Primero    7.0
Segundo    1.6
Tercero    4.0
Name: A, dtype: float64

In [ ]:
Valores["B"]

Primero     9.2
Segundo     2.4
Tercero    21.0
Name: B, dtype: float64

In [ ]:
Valores.iloc[0]

A    7.0
B    9.2
C    8.0
D    5.6
E    9.0
Name: Primero, dtype: float64

In [ ]:
Valores.iloc[0:2]

A    B    C
Primero  7.0  9.2  8.0
Segundo  1.6  2.4  1.7

In [ ]:
Valores.iloc[1:3]

A     B     C
Segundo  1.6   2.4   1.7
Tercero  4.0  21.0  32.0

In [ ]:
Valores.iloc[2:3]

A     B     C
Tercero  4.0  21.0  32.0

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
lista_1=np.random.randint(-1,2,size=5)


In [ ]:
lista_1

array([ 1,  1, -1,  1,  1])

In [ ]:
lista_2=np.random.randint(-30,50,size=5)

In [ ]:
lista_2

array([ 6, 33,  4, 14,  7])

In [ ]:
lista_3=np.random.randint(-45,70,size=5)

In [ ]:
lista_3

array([49, 26, 39,  1, -3])

In [ ]:
diccionario={'CapSmall':lista_1,'CapMedium':lista_2, 'CapLarge':lista_3}

In [ ]:
diccionario

{'CapSmall': array([ 1,  1, -1,  1,  1]),
 'CapMedium': array([ 6, 33,  4, 14,  7]),
 'CapLarge': array([49, 26, 39,  1, -3])}

In [ ]:
df=pd.DataFrame(diccionario)

In [ ]:
df

CapSmall  CapMedium  CapLarge
0         1          6        49
1         1         33        26
2        -1          4        39
3         1         14         1
4         1          7        -3

In [ ]:
dfindex = pd.DataFrame(diccionario,index = ["A", "B", "C", "D", "E"])

In [ ]:
dfindex

CapSmall  CapMedium  CapLarge
A         1          6        49
B         1         33        26
C        -1          4        39
D         1         14         1
E         1          7        -3

In [ ]:
dfindex.describe()

CapSmall  CapMedium   CapLarge
count  5.000000   5.000000   5.000000
mean   0.600000  12.800000  22.400000
std    0.894427  11.903781  22.908514
min   -1.000000   4.000000  -3.000000
25%    1.000000   6.000000   1.000000
50%    1.000000   7.000000  26.000000
75%    1.000000  14.000000  39.000000
max    1.000000  33.000000  49.000000

In [ ]:
df2=dfindex.drop(columns='CapSmall')
df2.iloc[1:3]

CapMedium  CapLarge
B         33        26
C          4        39

In [ ]:
df2.mean()

CapMedium    12.8
CapLarge     22.4
dtype: float64

In [ ]:
mayores = df2[df2['CapLarge']>10]

In [ ]:
mayores

CapMedium  CapLarge
A          6        49
B         33        26
C          4        39

In [ ]:
mayores.shape

(3, 2)

In [ ]:
items=diccionario.items()

In [ ]:
items

dict_items([('CapSmall', array([ 1,  1, -1,  1,  1])), ('CapMedium', array([ 6, 33,  4, 14,  7])), ('CapLarge', array([49, 26, 39,  1, -3]))])

In [ ]:
type(items)

dict_items

In [ ]:
df=pd.DataFrame(diccionario)

In [ ]:
df

CapSmall  CapMedium  CapLarge
0         1          6        49
1         1         33        26
2        -1          4        39
3         1         14         1
4         1          7        -3